# Generated by Django 6.0.3 on 2026-04-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document'], name='idx_chunk_document'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='idx_chunk_document_index'),
        ),
    ]
