# Generated by Django 6.0.3 on 2026-04-10 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['user'], name='idx_paper_user'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['user', '-updated_at'], name='idx_paper_user_updated'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['user', 'status'], name='idx_paper_user_status'),
        ),
        migrations.AddIndex(
            model_name='papersection',
            index=models.Index(fields=['paper', 'order'], name='idx_section_paper_order'),
        ),
    ]
