"""
Django settings for bakend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent  # 指向包含 accounts, agents 等应用的目录


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


from datetime import timedelta
import environ

env = environ.Env()
env_file = BASE_DIR.parent / '.env'  
environ.Env.read_env(env_file)


SECRET_KEY = env("SECRET_KEY")
DEBUG = env.bool("DEBUG", default=True) 
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "accounts",
    "agents",
    "chat",
    "documents",
    "pgvector",
    "analysis",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "agents.audit_middleware.AuditMiddleware",  # 审计中间件
]

AUDIT_LOG_ENABLED = True  # 启用审计日志


ROOT_URLCONF = "bakend.urls"



TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "bakend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 使用PostgreSQL进行生产环境（支持pgvector）
DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'agent_db',
        'USER': 'agent_user',
        'PASSWORD': 'agent_password',
        'HOST': 'db',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
      'rest_framework_simplejwt.authentication.JWTAuthentication', #JWT认证类
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', #全局权限设置，默认所有接口需要认证
    ),
    # 为TokenObtainPairView允许匿名访问
    'DEFAULT_PERMISSION_CLASSES_BY_VIEW': {
        'rest_framework_simplejwt.views.TokenObtainPairView': 'rest_framework.permissions.AllowAny',
        'rest_framework_simplejwt.views.TokenRefreshView': 'rest_framework.permissions.AllowAny',
    },
}

SIMPLE_JWT = {
  'ACCESS_TOKEN_LIFETIME': timedelta(days=1),  # 设置访问令牌的有效期
  'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # 设置刷新令牌的有效期
}


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # 前端开发服务器地址
    "http://127.0.0.1:5173",
]



# 添加Redis配置
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://localhost:6379/1',
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'PARSER_CLASS': 'redis.connection.HiredisParser',
            'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 50,
                'timeout': 20,
            },
            'MAX_CONNECTIONS': 1000,
            'PICKLE_VERSION': -1,
        },
        'KEY_PREFIX': 'research_agent',
        'TIMEOUT': 3600,  # 1小时默认超时
    }
}

# 会话缓存
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
SESSION_CACHE_ALIAS = 'default'

# 自定义缓存时间配置
CACHE_TTL = {
    'llm_response': 3600,      # LLM响应缓存1小时
    'embedding': 86400,         # 向量缓存24小时
    'search_result': 1800,      # 检索结果缓存30分钟
}